budget: 300

# unit is ms, it should be less than 1000
incoming:
  unit: 300
  per: 5
  max: 90000

# worldcup config, time between '1998-06-25 22:00:01' and '1998-06-27 22:00:00'
worldcup_start: '1998-06-26 10:00:01'
worldcup_end: '1998-06-27 00:00:01'

# azure config, day is between 1 and 14, offset is between 0 and 3000
azure_day: 8
azure_offset: 1500
azure_hashfunction_num: 10